Feature client-registration-activation
rizwans-cuelogic/poc pull request #1
Opened 2017-03-29 08:57 UTC by rizwans-cuelogic

Client-Registration:
  1.signup page for client using html,css and bootstrap.

Client-Activation:
  1.Client-activation by django admin.

Test-cases:
  1. Username should be 6 character long.
  2. password should be in range of 8 to 16 character long
  3. password should contain  at least 1 uppercase letter, 1 number ,1 lowercase letter.
  4. Email  should be a valid.
  5.password and confirm password should be same.

2017-03-29 09:26 UTC, ananthu-nair707 requested changes
Please make necessary changes. Do we need all the images that you have included in the PR? Are these static images or are they uploaded/tested by user?

2017-03-29 09:26 UTC, ananthu-nair707 commented on project1/project/ebs/models.py
> + 			mesagge = '%s Your account has been activated now. You can login and add blogs. Click here to login.' %(instance.username)
80 chars fix, spelling correction for message variable.

2017-03-29 09:26 UTC, ananthu-nair707 commented on project1/project/ebs/static/ebs/bootstrap-3.3.7-dist/js/npm.js
> +require('../../js/affix.js')
End of file fix.

2017-03-29 09:26 UTC, ananthu-nair707 commented on project1/project/ebs/static/ebs/css/home.css~
> +
Remove extra lines. Same change everywhere applicable.

2017-03-29 09:26 UTC, ananthu-nair707 commented on project1/project/ebs/models.py
> +		to true and if it is
proper alignment of comments.

2017-03-29 09:26 UTC, ananthu-nair707 commented on project1/project/ebs/models.py
> + 						[instance.email, "rizwan.shaikh@cuelogic.com"],
Please avoid hardcoded mail IDs here.

2017-03-29 10:01 UTC, rizwans-cuelogic commented
yes that images are  uploaded by user(client)

2017-04-03 13:26 UTC, deepalib-cuelogic commented on project4/project/project/settings.py
> +EMAIL_HOST_USER = 'rizwanshaikh2429@gmail.com'
use environment variables for EMAIL_HOST_USER, EMAIL_HOST_PASSWORD

2017-04-03 14:02 UTC, deepalib-cuelogic commented on project4/project/ebs/views.py
> +		f1=UserForm(request.POST or None,request.FILES or None)
use proper variable names.Name should describe the variable purpose.

2017-04-03 14:12 UTC, deepalib-cuelogic commented on project4/project/ebs/static/ebs/js/registration.js
> +    $.ajax({
remove commented code if not required

2017-04-03 14:13 UTC, deepalib-cuelogic commented on project4/project/ebs/views.py
> +		 	"""g = Group.objects.get(name='client')
remove commented code if not required

2017-04-03 14:15 UTC, deepalib-cuelogic commented on project4/project/ebs/views.py
> +# Create your views here.
Imports should be grouped in the following order:
standard library imports
related third party imports
local application/library specific imports
You should put a blank line between each group of imports.

2017-04-03 14:30 UTC, deepalib-cuelogic commented on project4/project/ebs/views.py
> +def regresult(request):
can we have better name than regresult? Functions should have descriptive meaningful names that relate to their purpose.

2017-04-03 14:38 UTC, deepalib-cuelogic commented on project4/project/ebs/views.py
> +	return render(request,'ebs/Registration.html')
keep these things consistent.rename template to registration.html

2017-04-03 14:40 UTC, deepalib-cuelogic commented on project4/project/ebs/views.py
> +def forgotpass(request):
Use the function naming rules: lowercase with words separated by underscores as necessary to improve readability.

2017-04-03 14:53 UTC, deepalib-cuelogic commented on project4/project/ebs/forms.py
> +
Arrange all imports grouped as per package and alphabetically

2017-04-03 14:54 UTC, deepalib-cuelogic commented on project4/project/ebs/models.py
> +
Arrange all imports grouped as per package and alphabetically

2017-04-03 14:57 UTC, deepalib-cuelogic commented on project4/project/ebs/models.py
> + 		print "caught"
add proper error message or print log the actual exception.refer https://docs.python.org/3/tutorial/errors.html

2017-04-03 15:00 UTC, deepalib-cuelogic commented on project4/project/ebs/views.py
> +	 	f1=UserForm();
Always surround these binary operators with a single space on either side

2017-04-03 15:02 UTC, deepalib-cuelogic commented on project4/project/ebs/views.py
> +	"""Views for registering client to plateform take UserForm and OrgForm save it to User object
avoid spelling mistakes

2017-04-03 15:05 UTC, deepalib-cuelogic commented on project4/project/ebs/templates/ebs/Registration.html
> +	<style>
add this in separate css file and include accordingly

2017-04-03 15:11 UTC, deepalib-cuelogic commented on project4/project/ebs/static/ebs/css/home.css~
> +.margin1{
remove this temporary css file

2017-04-03 15:12 UTC, deepalib-cuelogic commented on project4/project/ebs/models.py
> +	"""function take single user object check whether field is_active is changed
Limit all lines to a maximum of 80 characters.

2017-04-04 07:17 UTC, deepalib-cuelogic commented on project4/project/ebs/tests.py
> +from django.contrib.auth.models import User
remove unnecessary imports

2017-04-04 07:18 UTC, deepalib-cuelogic commented on project4/project/ebs/tests.py
> +
need valid test cases on view functions

2017-04-13 15:10 UTC, ananthu-nair707 approved these changes

2017-04-13 15:10 UTC, merged