BlogListing
rizwans-cuelogic/poc pull request #13
Opened 2017-04-27 12:03 UTC by rizwans-cuelogic

feature: shows list of blogs for particular Organisations as well as search for blogs and delete blogs.

2017-04-27 12:47 UTC, sagarp-cuelogic commented on project4/project/ebs/static/ebs/css/manage_blog.css
> +h1, h2, h3, h4, h5{
Move his CSS in common.css file

2017-04-27 12:48 UTC, sagarp-cuelogic commented on project4/project/ebs/static/ebs/css/manage_blog.css
>  .top-margin{
Remove this unwanted css as this class is not used anywhere.

2017-04-27 12:51 UTC, sagarp-cuelogic commented on project4/project/ebs/templates/ebs/manage_blog.html
> +						<a  id="delete-button" class=" btn btn2">
seperate checkbox and delete button in two th

2017-04-27 12:52 UTC, sagarp-cuelogic commented on project4/project/ebs/templates/ebs/manage_blog.html
> +					<th colspan="2">
remove colspan and split it in two th

2017-04-27 12:54 UTC, sagarp-cuelogic commented on project4/project/ebs/templates/ebs/manage_blog.html
> +						<div class="input-group search">
search is not aligned in center. use margins to align it to the center.

2017-04-27 12:56 UTC, sagarp-cuelogic commented on project4/project/ebs/templates/ebs/manage_blog.html
> +						<input type="text"class=" search1 form-control" placeholder="Search">
search1 class is not as per CSS naming conventions and give spacing in appropriate places.

2017-04-27 13:04 UTC, sagarp-cuelogic commented on project4/project/ebs/templates/ebs/manage_blog.html
> +				<tr class="warning no-result">
Text vertically not aligned properly.

2017-04-27 13:10 UTC, sagarp-cuelogic commented on project4/project/ebs/templates/ebs/paginator.html
> +<nav class="nav-center" aria-label="Page navigation">
remove the nav-center class, you can use text-center class from bootstrap.

2017-04-27 13:21 UTC, sagarp-cuelogic commented on project4/project/ebs/static/ebs/css/manage_blog.css
> +    margin-left:150px;
remove margin-left and set the search bar to the center.

2017-04-27 13:23 UTC, sagarp-cuelogic commented on project4/project/ebs/static/ebs/css/manage_blog.css
> +	margin-left:30px;
Remove margin and set the button in separate th to add spacing.

2017-04-27 13:24 UTC, sagarp-cuelogic commented on project4/project/ebs/static/ebs/css/manage_blog.css
> +.nav-center{
remove this class, you can use bootstrap class text-center.

2017-04-27 13:27 UTC, sagarp-cuelogic commented on project4/project/ebs/static/ebs/css/manage_blog.css
> +.table>tbody>tr>td> a{
remove duplicate css.

2017-04-27 13:29 UTC, sagarp-cuelogic commented on project4/project/ebs/static/ebs/css/manage_blog.css
> +.table>tbody>tr>td>h3>a{
Try to use shorthand CSS selectors.

2017-04-27 13:41 UTC, sagarp-cuelogic commented
- Remove top padding form td and add border-spacing to the table to add spacing between two rows.
 - Add width to the 2nd column in table to keep layout fix while searching.
 - Search bar alignment mess up when searching.
 - Remove extra spaces form the code.
 - Follow CSS naming conventions.

2017-04-27 14:09 UTC, sagarp-cuelogic commented on project4/project/ebs/static/ebs/css/manage_blog.css
> +    margin-top: 9px;
add "white-space:normal;" to resolve table width issue on small screen resolution.

2017-04-28 06:11 UTC, sagarp-cuelogic commented on project4/project/ebs/static/ebs/css/manage_blog.css
> +    margin-left:auto;
Write shorthand CSS for multiple css properties.

2017-04-28 06:12 UTC, sagarp-cuelogic commented on project4/project/ebs/static/ebs/css/manage_blog.css
> +	padding-top:20px;
Write shorthand CSS for multiple css properties.

2017-04-28 06:28 UTC, sagarp-cuelogic commented on project4/project/ebs/static/ebs/css/manage_blog.css
>  .image{
Change this class name as per CSS naming conventions.

2017-04-28 06:29 UTC, sagarp-cuelogic commented on project4/project/ebs/static/ebs/css/manage_blog.css
>  .text{
Change this class name as per CSS naming conventions.

2017-04-28 06:29 UTC, sagarp-cuelogic commented on project4/project/ebs/static/ebs/css/manage_blog.css
>  .btn2:hover{
Change this class name as per CSS naming conventions.

2017-04-28 06:32 UTC, sagarp-cuelogic commented
- Follow CSS naming conventions.
 - Remove spacing which are at wrong places and unwanted extra spacing from the code.
 - Error box not aligned on small screen.

2017-04-28 07:53 UTC, ananthu-nair707 requested changes
Code reviewed, please make necessary changes and add test cases.

2017-04-28 07:53 UTC, ananthu-nair707 commented on project4/project/ebs/models.py
> +
EOF (This is repeating in all PRs, take care of this without fail for upcoming PRs.)

2017-04-28 07:53 UTC, ananthu-nair707 commented on project4/project/ebs/views.py
> +    newdata = request.user
Since you are using request.user only once do you need to initilalize a new variable for it? As discussed try to avoid excess LOC.

2017-04-28 07:53 UTC, ananthu-nair707 commented on project4/project/project/urls.py
> +	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
EOF, all files please.

2017-04-28 07:53 UTC, ananthu-nair707 commented on project4/project/ebs/views.py
> +        paginator=Paginator(data,5)
Keep the 5 (pagination count) above as a global variable in settings which is configurable

2017-05-05 09:39 UTC, merged