Feature: catagory management
rizwans-cuelogic/poc pull request #7
Opened 2017-04-18 05:24 UTC by rizwans-cuelogic

2017-04-18 09:32 UTC, ananthu-nair707 requested changes

2017-04-18 09:32 UTC, ananthu-nair707 commented on project4/project/ebs/admin.py
> +class CatagoriesModelAdmin(admin.ModelAdmin):
Change "Catagory" to "Category" everywhere.

2017-04-18 09:32 UTC, ananthu-nair707 commented on project4/project/ebs/models.py
> +        print "can not send email"
Remove print statement here. In order to log a particular error use django's logging functionality.
https://docs.djangoproject.com/en/1.11/topics/logging/

2017-04-18 09:32 UTC, ananthu-nair707 commented on project4/project/ebs/models.py
> +    Draft=models.BooleanField(default=False)
keep variable names small case.

2017-04-18 09:32 UTC, ananthu-nair707 commented on project4/project/ebs/models.py
> +    description=models.TextField()
Is description nullable?

2017-04-18 09:32 UTC, ananthu-nair707 commented on project4/project/ebs/models.py
> +    name=models.CharField(max_length=125)
Is name nullable?

2017-04-18 09:32 UTC, ananthu-nair707 commented on project4/project/ebs/models.py
> +    published=models.DateTimeField()
Set default published date as datetime.now.

2017-04-18 10:16 UTC, rizwans-cuelogic commented on project4/project/ebs/models.py
> +    description=models.TextField()
description is required

2017-04-18 10:36 UTC, rizwans-cuelogic commented on project4/project/ebs/models.py
> +    description=models.TextField()
not nullable

2017-04-20 09:38 UTC, ananthu-nair707 requested changes
Please make final changes.

2017-04-20 09:38 UTC, ananthu-nair707 commented on project4/project/ebs/models.py
> +import logging
Maintain sequencing of imports.

2017-04-20 09:38 UTC, ananthu-nair707 commented on project4/project/ebs/models.py
> +
EOF fix here.

2017-04-20 12:39 UTC, ananthu-nair707 approved these changes

2017-04-20 12:40 UTC, merged